services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=developer
      - POSTGRES_DB=n8n
    volumes:
      - db-n8n-volume:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -h localhost -U developer -d n8n
      interval: 5s
      timeout: 5s
      retries: 10
    networks: 
      - n8n

  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=developer
      - DB_POSTGRESDB_PASSWORD=developer
    ports:
      - 5678:5678
    links:
      - postgres
    volumes:
      - n8n-volume:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy
    networks: 
      - n8n

volumes:
  db-n8n-volume:
  n8n-volume:

networks:
  n8n:
    name: n8n