version: '3'
services:
  nodered:
    image: nodered/node-red:latest
    ports:
      - 1880:1880
    environment:
      - NODE_RED_CREDENTIAL_SECRET=secret-key
      - TZ=America/Santiago
      - NODE_RED_ENABLE_PROJECTS=true
      # - FLOWS=/config/nodered/my-flows.json
    volumes:
      - ./nodered-data:/data:wo
volumes:
  nodered-data:
    driver: local