version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
      POSTGRES_DB: app
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "developer", "-d", "app"]
      interval: 5s
      retries: 5
    restart: unless-stopped
    networks: 
      - services
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@hola.ai
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data-volume:/var/lib/pgadmin
    networks: 
      - services
volumes:
  postgres-data-volume:
    driver: local
  pgadmin-data-volume:
    driver: local
networks:
  services:
    name: services
